#This is a movit contoller connecting follow_joint_trajectory controller withJointTrajectoryController
 controller_list:
 - name: robot_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
   - joint_1
   - joint_2
   - joint_3
   - joint_4

 
