arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_2
    - joint_3
    - joint_4
  gains:
    joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1